# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bvv81LrbrdFH7ZDo6B6lESaXVhXjep35
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris

# Load the Iris dataset
iris_sklearn = load_iris(as_frame=True)
iris_df = iris_sklearn.frame

# Rename columns for convenience
iris_df.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
iris_df['species'] = iris_df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# Pair Plot
sns.set(style="ticks")
pair_plot = sns.pairplot(iris_df, hue="species", markers=["o", "s", "D"])
plt.show()

# Histograms
iris_df.hist(edgecolor='black', linewidth=1.2, figsize=(12, 8))
plt.suptitle('Histograms of Iris Features', fontsize=16)
plt.show()

# Box Plots
plt.figure(figsize=(12, 6))
sns.boxplot(data=iris_df.drop(columns=['species']))
plt.title('Box Plots of Iris Features', fontsize=16)
plt.show()